baseURL: "/"
languageCode: "en-us"
languageLang: "en"
title: "Events A La Carte"

menu:
    main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about"
      weight: 2
    - name: "Weddings"
      url: "/weddings"
      weight: 3
    - name: "Corporate"
      url: "/corporate"
      weight: 4
    - name: "Social"
      url: "/social"
      weight: 5
    - name: "Careers"
      url: "/careers"
      weight: 6
    - name: "Contact"
      url: "/contact"
      weight: 7