baseURL: "/"
languageCode: "en-us"
languageLang: "en"
author: "Rima Chehab"
title: "Events A La Carte"

enableRobotsTXT: true
canonifyURLs: true

menu:
    main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about"
      weight: 2
    - name: "Weddings"
      url: "/weddings"
      weight: 3
    - name: "Corporate"
      url: "/corporate"
      weight: 4
    - name: "Social"
      url: "/social"
      weight: 5
    - name: "Careers"
      url: "/careers"
      weight: 6
    - name: "Contact"
      url: "/contact"
      weight: 7

params:
  tags:
    - "Event"
    - "Events"
    - "Events planning"
    - "Event planning"
    - "Wedding planning"
    - "Wedding"
    - "Baby shower"
    - "Baby showers"
    - "Birthday"
    - "Birthday party"
    - "Birthday parties"
    - "Party"
    - "Parties"
    - "Engagement"
    - "Engagement party"
    - "Engagement parties"
    - "Dinner party"
    - "Dinner parties"
  description: "Events and weddings planner"
