backend:
  name: git-gateway

media_folder: "img/uploads"

collections:
  - name: "weddings"
    label: "Weddings"
    folder: "site/content/weddings"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}