backend:
  name: git-gateway

media_library:
 name: uploadcare
 config:
   publicKey: f3f7f17b474208eaa29b
public_folder: "/img/uploads"

collections:
  - name: "settings"
    label: "Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "contact_details"
        label: "Contact Details"
        file: "site/data/contact_details.yml"
        fields:
          - {label: "Telephone Number", name: "phone", widget: "string", required: false}
          - {label: "Email", name: "email", widget: "string", required: false}
          - {label: "Link to Instagram", name: "instagram", widget: "string", required: false}
          - {label: "Link to Facebook", name: "facebook", widget: "string", required: false}
          - {label: "Link to Youtube", name: "youtube", widget: "string", required: false}
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "site/content/_index.md"
        fields:
          - label: "Main Section"
            name: "main_section"
            widget: "object"
            fields:
              - {label: "Section Image", name: "image", widget: "image"}
              - {label: "Section Content", name: "content", widget: "markdown"}
          - label: "Weddings Section"
            name: "weddings_section"
            widget: "object"
            fields:
              - {label: "Section Image", name: "image", widget: "image"}
              - {label: "Main Button Text", name: "button_text", widget: "string"}
          - label: "Corporate Events Section"
            name: "corporate_section"
            widget: "object"
            fields:
              - {label: "Section Image", name: "image", widget: "image"}
              - {label: "Main Button Text", name: "button_text", widget: "string"}
          - label: "Social Events Section"
            name: "social_section"
            widget: "object"
            fields:
              - {label: "Section Image", name: "image", widget: "image"}
              - {label: "Main Button Text", name: "button_text", widget: "string"}
  - name: "weddings"
    label: "Weddings"
    label_singular: "Wedding"
    folder: "site/content/weddings"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Theme"
        name: "theme"
        required: false
        widget: "object"
        fields:
          - {label: "Theme Name", name: "name", widget: "string"}
          - {label: "Theme Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Event Images", label_singular: "Event Image", name: "images", required: false, widget: "list", field: {label: "Image", name: "image", widget: "image"} }
      - label: "Event Testimonials"
        label_singular: "Event Testimonial"
        name: "testimonials"
        required: false
        widget: "list"
        fields:
          - {label: "Author", name: "author", widget: "string"}
          - {label: "Testimonial", name: "testimonial", widget: "text"}
  - name: "corporate"
    label: "Corporate Events"
    label_singular: "Corporate Event"
    folder: "site/content/corporate"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Theme"
        name: "theme"
        required: false
        widget: "object"
        fields:
          - {label: "Theme Name", name: "name", widget: "string"}
          - {label: "Theme Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Event Images", label_singular: "Event Image", name: "images", required: false, widget: "list", field: {label: "Image", name: "image", widget: "image"} }
      - label: "Event Testimonials"
        label_singular: "Event Testimonial"
        name: "testimonials"
        required: false
        widget: "list"
        fields:
          - {label: "Author", name: "author", widget: "string"}
          - {label: "Testimonial", name: "testimonial", widget: "text"}
  - name: "social"
    label: "Social Events"
    label_singular: "Social Event"
    folder: "site/content/social"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Theme"
        name: "theme"
        required: false
        widget: "object"
        fields:
          - {label: "Theme Name", name: "name", widget: "string"}
          - {label: "Theme Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Event Images", label_singular: "Event Image", name: "images", required: false, widget: "list", field: {label: "Image", name: "image", widget: "image"} }
      - label: "Event Testimonials"
        label_singular: "Event Testimonial"
        name: "testimonials"
        required: false
        widget: "list"
        fields:
          - {label: "Author", name: "author", widget: "string"}
          - {label: "Testimonial", name: "testimonial", widget: "text"}