backend:
  name: git-gateway

media_folder: "site/static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "contact_details"
    label: "Contact Details"
    file: "site/data/contact_details.yml"
    fields:
      - {label: "Telephone Number", name: "phone", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Link to Instagram", name: "instagram", widget: "string"}
      - {label: "Link to Facebook", name: "facebook", widget: "string"}
      - {label: "Link to Youtube", name: "youtube", widget: "string"}
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "site/content/_index.md"
        fields:
          - label: "Main Section"
            name: "main_section"
            widget: "object"
            fields:
              - {label: "Section Image", name: "image", widget: "image"}
              - {label: "Section Content", name: "content", widget: "markdown"}
          - label: "Weddings Section"
            name: "weddings_section"
            widget: "object"
            fields:
              - {label: "Section Image", name: "image", widget: "image"}
          - label: "Corporate Events Section"
            name: "corporate_section"
            widget: "object"
            fields:
              - {label: "Section Image", name: "image", widget: "image"}
          - label: "Social Events Section"
            name: "social_section"
            widget: "object"
            fields:
              - {label: "Section Image", name: "image", widget: "image"}
  - name: "weddings"
    label: "Weddings"
    label_singular: "Wedding"
    folder: "site/content/weddings"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Event Images", name: "images", widget: "list", field: {label: "Image", name: "image", widget: "image"} }
  - name: "corporate"
    label: "Corporate Events"
    label_singular: "Corporate Event"
    folder: "site/content/corporate"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Event Images", name: "images", widget: "list", field: {label: "Image", name: "image", widget: "image"} }
  - name: "social"
    label: "Social Events"
    label_singular: "Social Event"
    folder: "site/content/social"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Event Images", name: "images", widget: "list", field: {label: "Image", name: "image", widget: "image"} }