backend:
  name: git-gateway

media_library:
  name: uploadcare
  config:
    publicKey: f3f7f17b474208eaa29b
    tabs: file url gdrive gphotos instagram facebook dropbox
    multiple: true
    imagesOnly: true
    previewStep: true

public_folder: "/img/uploads"

collections:
  - name: "settings"
    label: "Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "contact_details"
        label: "Contact Details"
        file: "site/data/contact_details.yml"
        delete: false
        fields:
          - {label: "Telephone Number", name: "phone", widget: "string", required: false}
          - {label: "Email", name: "email", widget: "string", required: false}
          - {label: "Link to Instagram", name: "instagram", widget: "string", required: false}
          - {label: "Link to Facebook", name: "facebook", widget: "string", required: false}
          - {label: "Link to Youtube", name: "youtube", widget: "string", required: false}
  - name: "pages"
    label: "Pages"
    delete: false
    editor:
      preview: false
    files:
      - name: "home"
        label: "Home Page"
        file: "site/content/_index.md"
        delete: false
        fields:
          - label: "Main Section"
            name: "main_section"
            widget: "object"
            fields:
              - {label: "Section Image", name: "image", widget: "image"}
              - {label: "Section Content", name: "content", widget: "markdown"}
          - label: "Weddings Section"
            name: "weddings_section"
            widget: "object"
            fields:
              - {label: "Section Image", name: "image", widget: "image"}
              - {label: "Main Button Text", name: "button_text", widget: "string"}
              - {label: "Section Content", name: "content", widget: "markdown"}
          - label: "Corporate Events Section"
            name: "corporate_section"
            widget: "object"
            fields:
              - {label: "Section Image", name: "image", widget: "image"}
              - {label: "Main Button Text", name: "button_text", widget: "string"}
              - {label: "Section Content", name: "content", widget: "markdown"}
          - label: "Social Events Section"
            name: "social_section"
            widget: "object"
            fields:
              - {label: "Section Image", name: "image", widget: "image"}
              - {label: "Main Button Text", name: "button_text", widget: "string"}
              - {label: "Section Content", name: "content", widget: "markdown"}
      - name: "about"
        label: "About Page"
        file: "site/content/about/_index.md"
        delete: false
        editor:
          preview: false
        fields:
          - {label: "Content", name: "content", widget: "markdown"}
          - {label: "Image", name: "image", widget: "image"}
      - name: "careers"
        label: "Careers Page"
        file: "site/content/careers/_index.md"
        delete: false
        editor:
          preview: false
        fields:
          - label: "Vacant Positions"
            label_singular: "Vacant Position"
            name: "vacant_positions"
            widget: "list"
            fields:
              - {label: "Job Title", name: "job_title", widget: "string"}
              - {label: "Job Details", name: "job_details", widget: "markdown"}
              - {label: "Skills", name: "skills", widget: "markdown"}
              - {label: "Position", name: "position", widget: "string"}
              - {label: "Start", name: "start", widget: "string"}
  - name: "weddings"
    label: "Weddings"
    label_singular: "Wedding"
    editor:
      preview: false
    folder: "site/content/weddings"
    delete: false
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Theme"
        name: "theme"
        required: false
        widget: "object"
        fields:
          - {label: "Theme Name", name: "name", required: false, widget: "string"}
          - {label: "Theme Description", name: "description", required: false, widget: "text"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Event Images", name: "images", required: false, widget: "image"}
      - label: "Event Testimonials"
        label_singular: "Event Testimonial"
        name: "testimonials"
        required: false
        widget: "list"
        fields:
          - {label: "Author", name: "author", widget: "string"}
          - {label: "Testimonial", name: "testimonial", widget: "text"}
  - name: "corporate"
    label: "Corporate Events"
    label_singular: "Corporate Event"
    editor:
      preview: false
    folder: "site/content/corporate"
    delete: false
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Theme"
        name: "theme"
        required: false
        widget: "object"
        fields:
          - {label: "Theme Name", name: "name", required: false, widget: "string"}
          - {label: "Theme Description", name: "description", required: false, widget: "text"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Event Images", name: "images", required: false, widget: "image"}
      - label: "Event Testimonials"
        label_singular: "Event Testimonial"
        name: "testimonials"
        required: false
        widget: "list"
        fields:
          - {label: "Author", name: "author", widget: "string"}
          - {label: "Testimonial", name: "testimonial", widget: "text"}
  - name: "social"
    label: "Social Events"
    label_singular: "Social Event"
    editor:
      preview: false
    folder: "site/content/social"
    delete: false
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Theme"
        name: "theme"
        required: false
        widget: "object"
        fields:
          - {label: "Theme Name", name: "name", required: false, widget: "string"}
          - {label: "Theme Description", name: "description", required: false, widget: "text"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Event Images", name: "images", required: false, widget: "image"}
      - label: "Event Testimonials"
        label_singular: "Event Testimonial"
        name: "testimonials"
        required: false
        widget: "list"
        fields:
          - {label: "Author", name: "author", widget: "string"}
          - {label: "Testimonial", name: "testimonial", widget: "text"}